### ISSUE TITLE
18주차 Sprint #홍기

### ISSUE THREAD

**Issue by ohhonggi** [techeer-sv/Do-It-Algorithm-Study#140]
## Description
- [x] [섬 연결하기](https://school.programmers.co.kr/learn/courses/30/lessons/42861)
- [x] [정수 삼각형](https://school.programmers.co.kr/learn/courses/30/lessons/43105)

## To-do
- [x] Week 18 - Common problem solution
