### ISSUE TITLE
18주차 Sprint#일권

### ISSUE THREAD

**Issue by 1ilkwon** [techeer-sv/Do-It-Algorithm-Study#143]
## Description
- [ ] [섬 연결하기](https://school.programmers.co.kr/learn/courses/30/lessons/42861)
- [ ] [정수 삼각형](https://school.programmers.co.kr/learn/courses/30/lessons/43105)

## To-do
- [ ] Week 18 - Common problem solution
