### ISSUE TITLE
6주차/7주차 Sprint #서영

### ISSUE THREAD

**Issue by ksy990628** [techeer-sv/Do-It-Algorithm-Study#47]
## 6주차/7주차 Sprint ( 2023.05.19 ~ 2023.05.31 )
Chapter 범위 : 7장 리스트, 8주차 트리

## Description
- 문자열 탐색 알고리즘
- 리스트 문제 (3단계!!)
- 트리 문제

## To-do
- [ ] Week 6 - Common problem solution
- [ ] Week 6 - Sprint progress
- [ ] Week 7 - Common problem solution
- [ ] Week 7 - Sprint progress
