### ISSUE TITLE
6주차/7주차 Sprint #홍기

### ISSUE THREAD

**Issue by ohhonggi** [techeer-sv/Do-It-Algorithm-Study#48]
## 6/7주차 Sprint ( 2023.05.19 ~ 2023.05.31 )
Chapter 범위 : 7~8장

## Description
- [문자열 탐색](https://school.programmers.co.kr/learn/courses/30/lessons/60057) 문제
- [리스트](https://school.programmers.co.kr/learn/courses/30/lessons/81303) 문제
- [트리](https://school.programmers.co.kr/learn/courses/30/lessons/1844) 문제

## To-do
- [x] Week 6 - Common problem solution
- [ ] Week 6 - Sprint progress
- [x] Week 7 - Common problem solution
- [ ] Week 7 - Sprint progress
