### ISSUE TITLE
6주차/7주차 Sprint #일권

### ISSUE THREAD

**Issue by 1ilkwon** [techeer-sv/Do-It-Algorithm-Study#50]
## 6/7주차 Sprint ( 2023.05.19 ~ 2023.05.31 )
Chapter 범위 : 7~8장

## Description
[문자열 탐색](https://school.programmers.co.kr/learn/courses/30/lessons/60057) 문제
[리스트](https://school.programmers.co.kr/learn/courses/30/lessons/81303) 문제
[트리](https://school.programmers.co.kr/learn/courses/30/lessons/1844) 문제

## To-do
- [ ] Week 6 - Common problem solution
- [ ] Week 6 - Sprint progress
- [ ] Week 7 - Common problem solution
- [ ] Week 7 - Sprint progress
